const config = {
    COGNITO_USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
    COGNITO_CLIENT_ID: process.env.REACT_APP_COGNITO_CLIENT_ID,
    IDENTITY_POOL_ID: process.env.REACT_APP_IDENTITY_POOL_ID,
    LAMBDAS: {
        CAESAR_CIPHER_API: process.env.REACT_APP_CAESAR_CIPHER_API,
        DAL_SAFE_EXPRESS_API: process.env.REACT_APP_DAL_SAFE_EXPRESS_API
    },
    CLOUD_FUNCTIONS: {
        SAVE_SECURITY_ANSWER_API: process.env.REACT_APP_SAVE_SECURITY_ANSWER_API,
        PUB_SUB_API: process.env.REACT_APP_PUB_SUB_API,
        GET_SECURITY_ANSWER_API: process.env.REACT_APP_GET_SECURITY_ANSWER_API
    }
}

export default config;